assembly:
  accession: GCA_903992545.1
  alias: mPipPip1.1
  bioproject: PRJEB39564
  biosample: SAMEA994724
  file: /lustre/scratch123/tol/teams/blaxter/users/rc28/2021/btk/by_accession/GCA_903992545.1/assembly/GCA_903992545.1.fasta.gz
  level: chromosome
  prefix: CAJEUD01
  scaffold-count: 323
  span: 1763439233
busco:
  lineage_dir: /lustre/scratch123/tol/teams/blaxter/users/rc28/2021/databases/busco
  lineages:
    - laurasiatheria_odb10
    - eutheria_odb10
    - mammalia_odb10
    - tetrapoda_odb10
    - vertebrata_odb10
    - metazoa_odb10
    - eukaryota_odb10
revision: 0
settings:
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_overlap: 500
  chunk: 1000000
  tmp: /tmp
similarity:
  databases:
    - local: /lustre/scratch123/tol/teams/blaxter/users/rc28/2021/databases/uniprot
      name: reference_proteomes
  defaults:
    evalue: 1.0e-25
    mask_ids:
      - 27671
    max_target_seqs: 10
    root: 1
  taxrule: bestdist
taxon:
  class: Mammalia
  family: Vespertilionidae
  genus: Pipistrellus
  kingdom: Metazoa
  name: Pipistrellus pipistrellus
  order: Chiroptera
  phylum: Chordata
  superkingdom: Eukaryota
  taxid: "59474"
version: 1
